Repository VATSSA-Operations/Sector-Files, pull requests merged in 2022-06, with the labels that each got.

#15 AfV Plugin Changes
  DGAC Accra/DGAC Advanced.prf
  DGAC Accra/DGAC.prf
  DNKK Kano/DNKK Advanced.prf
  DNKK Kano/DNKK.prf
  FAXX South Africa/FASA.prf
  FAXX South Africa/FASA/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FAXX South Africa/FASA/Plugins/AfvEuroScopeBridge.dll
  FBGR Gaborone/FBGR.prf
  FBGR Gaborone/FBGR/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FCCC Brazzaville/FCCC Advanced.prf
  FCCC Brazzaville/FCCC.prf
  FIMM Mauritius/FIMM.prf
  FIMM Mauritius/FIMM/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FLFI Lusaka/FLFI.prf
  FLFI Lusaka/FLFI/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FMMM Antananarivo/FMMM.prf
  FMMM Antananarivo/FMMM/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FNAN Luanda/FNAN.prf
  FNAN Luanda/FNAN/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FQBE Beira/FQBE.prf
  FQBE Beira/FQBE/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FSSS Seychelles/FSSS.prf
  FSSS Seychelles/FSSS/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FVHF Harare/FVHF.prf
  FVHF Harare/FVHF/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FWLL Lilongwe/FWLL.prf
  FWLL Lilongwe/FWLL/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FYWH Windhoek/FYWH.prf
  FYWH Windhoek/FYWH/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  FZZA Kinshasa/FZZA.prf
  FZZA Kinshasa/FZZA/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  GOOO Dakar/GOOO Advanced.prf
  GOOO Dakar/GOOO.prf
  GVSC Sal/GVSC Advanced.prf
  GVSC Sal/GVSC.prf
  HKNA Nairobi/HKNA.prf
  HKNA Nairobi/HKNA/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  HTDC Dar es Salaam/HTDC.prf
  HTDC Dar es Salaam/HTDC/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
  HUEC Entebbe/HUEC.prf
  HUEC Entebbe/HUEC/Plugins/AfVEuroScopeBridge/AfvEuroScopeBridge.dll
Labels: enhancement

#31 Update TopSkyMaps.txt
  DGAC Accra/DGAC/Plugins/TopSky/TopSkyMaps.txt
Labels: bug

#37 Shared Resources Folder
  _Shared Resources/GroundRadar/GroundRadar-SETTINGS.md
  _Shared Resources/GroundRadar/GroundRadar-STANDS-AirlineGroups.md
  _Shared Resources/Settings/ES-Lists-Advanced-ARRIVAL.md
  _Shared Resources/Settings/ES-Lists-Advanced-DEPARTURE.md
  _Shared Resources/Settings/ES-Lists-Advanced-SEL.md
  _Shared Resources/Settings/ES-Lists-Advanced-SIL.md
  _Shared Resources/Settings/ES-Lists-Advanced-STARTUP.md
  _Shared Resources/Settings/VATSSA_ArrivalList_Advanced.txt
  _Shared Resources/Settings/VATSSA_Conflict_Advanced.txt
  _Shared Resources/Settings/VATSSA_DepartureList_Advanced.txt
  _Shared Resources/Settings/VATSSA_FPList_Advanced.txt
  _Shared Resources/Settings/VATSSA_General_Advanced.txt
  _Shared Resources/Settings/VATSSA_PilotingList_Advanced.txt
  _Shared Resources/Settings/VATSSA_Plugins_Advanced.txt
  _Shared Resources/Settings/VATSSA_Screen_Advanced.txt
  _Shared Resources/Settings/VATSSA_SectorExitList_Advanced.txt
  _Shared Resources/Settings/VATSSA_SectorInboundList_Advanced.txt
  _Shared Resources/Settings/VATSSA_Symbology_Advanced.txt
  _Shared Resources/Settings/VATSSA_Tags_Advanced.txt
  _Shared Resources/TopSky/Maps/TopSkyMaps-0-STRUCTURE.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-1-COLORS.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-11-AIRSPACE.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-13-MSA.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-2-SYMBOLS.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-3-SETTINGS.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-4-FIR.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-5-ARRIVALS.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-6-APPROACHES.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-7-DEPARTURES.md
  _Shared Resources/TopSky/Maps/TopSkyMaps-GEO.md
  _Shared Resources/TopSky/Settings/TopSkySettings-0-MSAW.md
  _Shared Resources/TopSky/Settings/TopSkySettings-0-NOTAMS.md
  _Shared Resources/TopSky/Settings/TopSkySettings-0-STRUCTURE.md
  _Shared Resources/TopSky/Settings/TopSkySettings-1-SETTINGS.md
  _Shared Resources/TopSky/Settings/TopSkySettings-10-WX-SERVER-SETTINGS.md
  _Shared Resources/TopSky/Settings/TopSkySettings-2-COLORS.md
  _Shared Resources/TopSky/Settings/TopSkySettings-3-VISUAL.md
  _Shared Resources/TopSky/Settings/TopSkySettings-4-TRACK.md
  _Shared Resources/TopSky/Settings/TopSkySettings-5-VECTORS.md
  _Shared Resources/TopSky/Settings/TopSkySettings-6-HOLDINGS.md
  _Shared Resources/TopSky/Settings/TopSkySettings-7-CPDLC.md
  _Shared Resources/TopSky/Settings/TopSkySettings-8-RDF.md
  _Shared Resources/TopSky/Settings/TopSkySettings-9-RWY-APP-LINES.md
Labels: documentation

#41 Adds stands for GR on DNAA
  DNKK Kano/DNKK/Plugins/GroundRadar/GRpluginStands.txt
Labels: bug

#48 Update TopSkyMaps.txt
  FASA South Africa/FASA/Plugins/TopSky/TopSkyMaps.txt
Labels: bug

#73 20220623 v4
  FZZA Kinshasa/FZZA-Test-Package_20220623151344-220601-0005.ese
  FZZA Kinshasa/FZZA-Test-Package_20220623151344-220601-0005.sct
  FZZA Kinshasa/FZZA/ASR/FZAA AD GR.asr
  FZZA Kinshasa/FZZA/ASR/FZAA APP TS.asr
  FZZA Kinshasa/FZZA/Plugins/GroundRadar/GRpluginMaps.txt
  FZZA Kinshasa/FZZA/Plugins/GroundRadar/GRpluginSettings.txt
  FZZA Kinshasa/FZZA/Plugins/TopSky/TopSkyMaps.txt
Labels: enhancement

#61 Topsky maps updates
  FCCC Brazzaville/FCCC/Plugins/TopSky/TopSkyMaps.txt
Labels: bug

#57 AIRAC 2207 Bug Fixes
  DNKK Kano/DNKK/ASR/DNAA AD GR.asr
  DNKK Kano/DNKK/ASR/DNAA APP TS.asr
  DNKK Kano/DNKK/Plugins/TopSky/TopSkyMaps.txt
  FCCC Brazzaville/FCCC/ASR/FEFF AD GR.asr
  HTDC Dar es Salaam/HTDC/Plugins/TopSky/TopSkySettings.txt
Labels: bug

#30 FLFI Refresh v1
  FLFI Lusaka/FLFI-Package_20220616134408-220601-0001.rwy
  FLFI Lusaka/FLFI/ASR/1 FLFI CTR TS.asr
  FLFI Lusaka/FLFI/ASR/FLFI_CTR.asr
  FLFI Lusaka/FLFI/ASR/FLKK AD GR.asr
  FLFI Lusaka/FLFI/ASR/FLKK APP TS.asr
  FLFI Lusaka/FLFI/Alias/alias.txt
  FLFI Lusaka/FLFI/Plugins/GroundRadar/GRpluginSettings.txt
  FLFI Lusaka/FLFI/Plugins/TopSky/TopSkyMaps.txt
  FLFI Lusaka/FLFI/Plugins/TopSky/TopSkySettings.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_ArrivalList_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_Conflict_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_DepartureList_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_FPList_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_General_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_PilotingList_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_Plugins_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_Screen_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_SectorExitList_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_SectorInboundList_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_Symbology_Advanced.txt
  FLFI Lusaka/FLFI/Settings/VATSSA_Tags_Advanced.txt
Labels: enhancement

#101 Profilex.txt Updates
  DGAC Accra/DGAC/Settings/Profiles.txt
  FLFI Lusaka/FLFI/Settings/Profiles.txt
  FVHF Harare/FVHF/Settings/Profiles.txt
  FWLL Lilongwe/FWLL/Settings/Profiles.txt
  HKNA Nairobi/HKNA/Settings/Profiles.txt
Labels: enhancement

#105 HUEN TopSky Updates
  FNAN Luanda/FNAN/Plugins/TopSky/TopSkySettings.txt
  HKNA Nairobi/HKNA/Plugins/TopSky/TopSkySettings.txt
  HTDC Dar es Salaam/HTDC/Plugins/TopSky/TopSkySettings.txt
  HUEC Entebbe/HUEC/ASR/1 HUEC CTR TS.asr
  HUEC Entebbe/HUEC/ASR/HUEN APP TS.asr
  HUEC Entebbe/HUEC/Plugins/TopSky/ICAO_Airlines.txt
  HUEC Entebbe/HUEC/Plugins/TopSky/ICAO_Airports.txt
  HUEC Entebbe/HUEC/Plugins/TopSky/TopSkyAirspace.txt
  HUEC Entebbe/HUEC/Plugins/TopSky/TopSkyAreas.txt
  HUEC Entebbe/HUEC/Plugins/TopSky/TopSkyMaps.txt
  HUEC Entebbe/HUEC/Plugins/TopSky/TopSkySettings.txt
  _Shared Resources/TopSky/Airspace/TopSkyAirspace - Copy.txt
  _Shared Resources/TopSky/Airspace/TopSkyAirspace-0-STRUCTURE.md
  _Shared Resources/TopSky/Airspace/TopSkyAirspace.txt
  _Shared Resources/TopSky/Areas/TopSkyAreas.txt
  _Shared Resources/TopSky/Maps/TopSkyMaps-11-AIRSPACE.md
Labels: enhancement

#95 New vATIS Profiles
  _vATIS/HKNA/vATIS Profile - HKMO.json
  _vATIS/HKNA/vATIS Profile - HKMO.zip
Labels: enhancement

#104 Main huen hkmo
  HKNA Nairobi/HKNA/Plugins/GroundRadar/GRpluginStands.txt
  HUEC Entebbe/HUEC/Plugins/GroundRadar/GRpluginStands.txt
Labels: enhancement

#106 Ground layouts development
  _Ground Layouts/FBGR/FBMN/FBGR-FBMN-v0.1-20220625.sct.txt
  _Ground Layouts/FBGR/FBMN/FBGR-FBMN.kmz
  _Ground Layouts/FBGR/FBMN/FNAN-FHSH-v0.1-20220625.sct.txt
  _Ground Layouts/FNAN/FHSH/FNAN-FHSH.kmz
  _Ground Layouts/FZZA/FZAA/FZZA-FZAA.kmz
  _Ground Layouts/FZZA/FZAA/FZZA-FZAA_v0-1_20220623.sct.txt
Labels: enhancement

#125 Multiple Updates
  FASA South Africa/FASA/Plugins/TopSky/TopSkyAirspace.txt
  FBGR Gaborone/FBGR/Plugins/TopSky/TopSkyAirspace.txt
  FLFI Lusaka/FLFI/Plugins/TopSky/TopSkyAirspace.txt
  FMMM Antananarivo/FMMM/Plugins/TopSky/TopSkyAirspace.txt
  FMMM Antananarivo/FMMM/Plugins/TopSky/TopSkyMaps.txt
  FMMM Antananarivo/FMMM/Plugins/TopSky/TopSkySTCA.txt
  FNAN Luanda/FNAN/Plugins/TopSky/TopSkyAirspace.txt
  FNAN Luanda/FNAN/Plugins/TopSky/TopSkyMaps.txt
  FQBE Beira/FQBE/Plugins/TopSky/TopSkyAirspace.txt
  FSSS Seychelles/FSSS/Plugins/TopSky/TopSkyAirspace.txt
  FVHF Harare/FVHF/Plugins/TopSky/TopSkyAirspace.txt
  FYWH Windhoek/FYWH/Plugins/TopSky/TopSkyAirspace.txt
  FZZA Kinshasa/FZZA/Plugins/TopSky/TopSkyAirspace.txt
  HKNA Nairobi/HKNA/Plugins/GroundRadar/GRpluginStands.txt
  HKNA Nairobi/HKNA/Plugins/TopSky/TopSkyAirspace.txt
  HTDC Dar es Salaam/HTDC/Plugins/TopSky/TopSkyAirspace.txt
  HUEC Entebbe/HUEC/Plugins/GroundRadar/GRpluginStands.txt
  HUEC Entebbe/HUEC/Plugins/TopSky/TopSkyAirspace.txt
  HUEC Entebbe/HUEC/Plugins/TopSky/TopSkyAreas.txt
  HUEC Entebbe/HUEC/Plugins/TopSky/TopSkyMaps.txt
  _Ground Layouts/FCCC/FEFF/FCCC-FEFF-WIP.kmz
  _Ground Layouts/FCCC/FEFF/FCCC-FEFF-v0.1.kmz
  _Ground Layouts/FCCC/FEFF/FCCC-FEFF-v0.1.sct.txt
  _Shared Resources/GroundRadar/Maps/GRpluginMaps 0-STRUCTURE.md
  _Shared Resources/Settings/ASR/1 HUEC CTR TS.asr
  _Shared Resources/TopSky/Airspace/TopSkyAirspace - Copy.txt
  _Shared Resources/TopSky/Airspace/TopSkyAirspace-0-STRUCTURE.md
  _Shared Resources/TopSky/Airspace/TopSkyAirspace.txt
  _Shared Resources/TopSky/Areas/TopSkyAreas.txt
  _Shared Resources/TopSky/Maps/TopSkyMaps-0-STRUCTURE.md
Labels: enhancement

#134 FSSS Sector Updates
  .gitignore
  FSSS Seychelles/FSSS/ASR/1 FSSS CTR TS.asr
  FSSS Seychelles/FSSS/ASR/FSIA AD GR.asr
  FSSS Seychelles/FSSS/ASR/FSIA APP TS.asr
  FSSS Seychelles/FSSS/ICAO/ICAO_Airlines.txt
  FSSS Seychelles/FSSS/Plugins/GroundRadar/GRpluginMaps.txt
  FSSS Seychelles/FSSS/Plugins/GroundRadar/GRpluginSettings.txt
  FSSS Seychelles/FSSS/Plugins/TopSky/TopSkyAirspace.txt
  FSSS Seychelles/FSSS/Plugins/TopSky/TopSkyMaps.txt
  _Status/FSSS.md
Labels: enhancement

#175 Adds more GR stand data for GOOO and FSSS
  FSSS Seychelles/FSSS/Plugins/GroundRadar/GRpluginStands.txt
  GOOO Dakar/GOOO/Plugins/GroundRadar/GRpluginStands.txt
  HUEC Entebbe/HUEC/Plugins/GroundRadar/GRpluginStands.txt
Labels: GOOO, FSSS
